#!/usr/bin/env php
<?php

require(__DIR__ . '/config/helpers.php');
require(__DIR__ . '/vendor/autoload.php');

try {
    (new Dotenv\Dotenv(__DIR__ . '/config'))->load();
} catch (Dotenv\Exception\InvalidPathException $e) {
}

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');

$config = require(__DIR__ . '/config/console.php');
$application = new yii\console\Application($config);
exit($application->run());